---
name: movie_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.5.3
dependencies:
  bordered_text: null
  cupertino_icons: ^1.0.8
  dartz: null
  dio: null
  flutter:
    sdk: flutter
  flutter_bloc: null
  freezed_annotation: ^2.4.4
  get_it: ^7.2.0
  injectable: ^1.5.3
  json_annotation: null
  json_serializable: null
  video_player: ^2.6.1
  share_plus: ^10.1.2


dev_dependencies:
  build_runner: null
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: null
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true
