---
name: movie_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bordered_text:
  flutter_bloc:
  json_serializable:
  json_annotation:
  dartz:
  dio:
  get_it: ^7.2.0
  injectable: ^1.5.3

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  flutter_lints: ^4.0.0
  injectable_generator: ^1.5.3



flutter:
  uses-material-design: true
